package main

import (
	"fmt"
	"jm-CICO/handlers"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/loketcabangjawatengah", handlers.LoketCabangHandler)
	http.HandleFunc("/samsatkendal", handlers.SamsatKendalHandler)
	http.HandleFunc("/samsatdemak", handlers.SamsatDemakHandler)

	http.HandleFunc("/samsatpurwodadi", handlers.SamsatPurwodadiHandler)
	http.HandleFunc("/samsatungaran", handlers.SamsatUngaranHandler)
	http.HandleFunc("/samsatsalatiga", handlers.SamsatSalatigaHandler)
	http.HandleFunc("/samsatlokperwsra", handlers.SamsatLokPerwSRAHandler)
	http.HandleFunc("/samsatsurakarta", handlers.SamsatSurakartaHandler)
	http.HandleFunc("/samsatklaten", handlers.SamsatKlatenHandler)
	http.HandleFunc("/samsatboyolali", handlers.SamsatBoyolaliHandler)
	http.HandleFunc("/samsatsragen", handlers.SamsatSragenHandler)
	http.HandleFunc("/samsatprambanan", handlers.SamsatPrambananHandler) #a serv
	http.HandleFunc("/samsatdelanggu", handlers.SamsatDelangguHandler)
	http.HandleFunc("/samsatlokpwkmgl", handlers.SamsatLokPwkMGLHandler)
	http.HandleFunc("/samsatmagelang", handlers.SamsatMagelangHandler)
	http.HandleFunc("/samsatpurworejo", handlers.SamsatPurworejoHandler)
	http.HandleFunc("/samsatkebumen", handlers.SamsatKebumenHandler)
	http.HandleFunc("/samsattemanggung", handlers.SamsatTemanggungHandler)
	http.HandleFunc("/samsatwonosobo", handlers.SamsatWonosoboHandler)
	http.HandleFunc("/samsatmungkid", handlers.SamsatMungkidHandler)
	http.HandleFunc("/samsatbagelen", handlers.SamsatBagelenHandler)
	http.HandleFunc("/samsatlokprwpwt", handlers.SamsatLokPrwPWTHandler)
	http.HandleFunc("/samsat/purwokerto", handlers.SamsatPurwokertoHandler)
	http.HandleFunc("/samsat/purbalingga", handlers.SamsatPurbalinggaHandler)
	http.HandleFunc("/samsat/banjarnegara", handlers.SamsatBanjarnegaraHandler)
	http.HandleFunc("/samsat/majenang", handlers.SamsatMajenangHandler)
	http.HandleFunc("/samsat/cilacap", handlers.SamsatCilacapHandler)
	http.HandleFunc("/samsat/wangon", handlers.SamsatWangonHandler)
	http.HandleFunc("/samsat/lokprwpkl", handlers.SamsatLokPrwPklHandler)
	http.HandleFunc("/samsat/pekalongan", handlers.SamsatPekalonganHandler)
	http.HandleFunc("/samsat/pemalang", handlers.SamsatPemalangHandler)
	http.HandleFunc("/samsat/tegal", handlers.SamsatTegalHandler)
	http.HandleFunc("/samsat/brebes", handlers.SamsatBrebesHandler)
	http.HandleFunc("/samsat/batang", handlers.SamsatBatangHandler)
	http.HandleFunc("/samsat/kajen", handlers.SamsatKajenHandler)
	http.HandleFunc("/samsat/slawi", handlers.SamsatSlawiHandler)
	http.HandleFunc("/samsat/bumiayu", handlers.SamsatBumiayuHandler)
	http.HandleFunc("/samsat/tanjung", handlers.SamsatTanjungHandler)
	http.HandleFunc("/samsat/lokprwpti", handlers.SamsatLokPrwPtiHandler)
	http.HandleFunc("/samsat/pati", handlers.SamsatPatiHandler)
	http.HandleFunc("/samsat/kudus", handlers.SamsatKudusHandler)
	http.HandleFunc("/samsat/jepara", handlers.SamsatJeparaHandler)
	http.HandleFunc("/samsat/rembang", handlers.SamsatRembangHandler)
	http.HandleFunc("/samsat/blora", handlers.SamsatBloraHandler)
	http.HandleFunc("/samsat/cepu", handlers.SamsatCepuHandler)
	http.HandleFunc("/samsat/lokprwsmg", handlers.SamsatLokPrwSmgHandler)
	http.HandleFunc("/samsat/semarang1", handlers.SamsatSemarang1Handler)
	http.HandleFunc("/samsat/semarang2", handlers.SamsatSemarang2Handler)
	http.HandleFunc("/samsat/semarang3", handlers.SamsatSemarang3Handler)
	http.HandleFunc("/samsat/lokprwskh", handlers.SamsatLokPrwSkhHandler)
	http.HandleFunc("/samsat/sukoharjo", handlers.SamsatSukoharjoHandler)
	http.HandleFunc("/samsat/karanganyar", handlers.SamsatKaranganyarHandler)
	http.HandleFunc("/samsat/wonogiri", handlers.SamsatWonogiriHandler)
	http.HandleFunc("/samsat/purwantoro", handlers.SamsatPurwantoroHandler)
	http.HandleFunc("/samsat/baturetno", handlers.SamsatBaturetnoHandler)

	fmt.Println("Server started on http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", nil))
}